// Generated by kv260/regmap.py; do not edit.
/* verilator lint_off UNUSEDPARAM */
package kv260_regs_pkg;
    localparam logic [31:0] BW_ID_VALUE = 32'h4B564257;
    localparam logic [31:0] ACC_ID_VALUE = 32'h4B564143;
    localparam logic [31:0] VERSION_VALUE = 32'h00010000;
    localparam logic [11:0] BW_ID = 12'h000;  // RO: 0x4B564257 ('KVBW')
    localparam logic [11:0] BW_VERSION = 12'h004;  // RO: major<<16 | minor
    localparam logic [11:0] BW_CTRL = 12'h008;  // WO: bit0 RD_START, bit1 WR_START, bit31 SOFT_RESET (all self-clearing)
    localparam logic [11:0] BW_STATUS = 12'h00C;  // RO: bit0 RD_BUSY, bit1 WR_BUSY, [11:8] RD_ERR, [15:12] WR_ERR, bit16 CFG_ERR
    localparam logic [11:0] BW_RD_ADDR_LO = 12'h010;  // RW: read start byte address [31:0] (HP ports x beat aligned)
    localparam logic [11:0] BW_RD_ADDR_HI = 12'h014;  // RW: read start byte address [48:32]
    localparam logic [11:0] BW_RD_BYTES = 12'h018;  // RW: bytes per read pass (multiple of HP ports x beat, 64 B for 4x128 bit)
    localparam logic [11:0] BW_RD_REPEAT = 12'h01C;  // RW: number of back-to-back read passes (0 is treated as 1)
    localparam logic [11:0] BW_WR_ADDR_LO = 12'h020;  // RW: write start byte address [31:0] (beat aligned)
    localparam logic [11:0] BW_WR_ADDR_HI = 12'h024;  // RW: write start byte address [48:32]
    localparam logic [11:0] BW_WR_BYTES = 12'h028;  // RW: bytes to write (multiple of the beat)
    localparam logic [11:0] BW_WR_SEED = 12'h02C;  // RW: pattern: 32-bit word k of the write = WR_SEED + k
    localparam logic [11:0] BW_RD_CYCLES = 12'h030;  // RO: clock cycles from RD_START until the last beat
    localparam logic [11:0] BW_RD_BEATS = 12'h034;  // RO: beats received
    localparam logic [11:0] BW_RD_SUM = 12'h038;  // RO: sum of all little-endian 32-bit words read, mod 2^32
    localparam logic [11:0] BW_WR_CYCLES = 12'h03C;  // RO: clock cycles from WR_START until the last BRESP
    localparam logic [11:0] BW_CAPS = 12'h040;  // RO: [3:0] HP ports, [15:8] data width/8, [23:16] max burst beats-1
    localparam logic [11:0] ACC_ID = 12'h000;  // RO: 0x4B564143 ('KVAC')
    localparam logic [11:0] ACC_VERSION = 12'h004;  // RO: major<<16 | minor
    localparam logic [11:0] ACC_CTRL = 12'h008;  // WO: bit0 START (run program once), bit31 SOFT_RESET
    localparam logic [11:0] ACC_STATUS = 12'h00C;  // RO: bit0 BUSY, bit1 DONE (sticky until START), [15:8] ERROR code
    localparam logic [11:0] ACC_IMAGE_BASE_LO = 12'h010;  // RW: DMA device address of the DDR image [31:0] (64 B aligned)
    localparam logic [11:0] ACC_IMAGE_BASE_HI = 12'h014;  // RW: DMA device address of the DDR image [48:32]
    localparam logic [11:0] ACC_PROG_WORDS = 12'h018;  // RW: number of 128-bit instructions in program memory
    localparam logic [11:0] ACC_TOKEN = 12'h01C;  // RW: input token id (BATCH=1)
    localparam logic [11:0] ACC_POS = 12'h020;  // RW: position of the token (cached rows before it)
    localparam logic [11:0] ACC_RESULT = 12'h024;  // RO: argmax token of the last run
    localparam logic [11:0] ACC_CYCLES = 12'h028;  // RO: clock cycles of the last run
    localparam logic [11:0] ACC_ERR_PC = 12'h02C;  // RO: instruction index that raised ERROR
    localparam logic [11:0] ACC_PROG_ADDR = 12'h030;  // RW: program memory word pointer for PROG_DATA writes
    localparam logic [11:0] ACC_PROG_DATA = 12'h034;  // WO: writes 32 bits at PROG_ADDR (4 writes per instruction, low first), auto-increment
endpackage
/* verilator lint_on UNUSEDPARAM */
