// Generated by kv260/gen_wrappers.py; do not edit. Verilog-2001 shell for IP Integrator.
// Instantiates bw_test_top (SystemVerilog) with 4 HP ports; hp0 also writes.
module kv260_bw_wrapper (
    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk CLK" *)
    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF s_axi_ctrl:m_axi_hp0:m_axi_hp1:m_axi_hp2:m_axi_hp3, ASSOCIATED_RESET rst_n" *)
    input  wire clk,
    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 rst_n RST" *)
    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)
    input  wire rst_n,
    input  wire s_axi_ctrl_awvalid,
    output wire s_axi_ctrl_awready,
    input  wire [11:0] s_axi_ctrl_awaddr,
    input  wire s_axi_ctrl_wvalid,
    output wire s_axi_ctrl_wready,
    input  wire [31:0] s_axi_ctrl_wdata,
    input  wire [3:0] s_axi_ctrl_wstrb,
    output wire s_axi_ctrl_bvalid,
    input  wire s_axi_ctrl_bready,
    output wire [1:0] s_axi_ctrl_bresp,
    input  wire s_axi_ctrl_arvalid,
    output wire s_axi_ctrl_arready,
    input  wire [11:0] s_axi_ctrl_araddr,
    output wire s_axi_ctrl_rvalid,
    input  wire s_axi_ctrl_rready,
    output wire [31:0] s_axi_ctrl_rdata,
    output wire [1:0] s_axi_ctrl_rresp,
    output wire m_axi_hp0_arvalid,
    input  wire m_axi_hp0_arready,
    output wire [48:0] m_axi_hp0_araddr,
    output wire [7:0] m_axi_hp0_arlen,
    output wire [2:0] m_axi_hp0_arsize,
    output wire [1:0] m_axi_hp0_arburst,
    output wire [3:0] m_axi_hp0_arcache,
    output wire [2:0] m_axi_hp0_arprot,
    input  wire m_axi_hp0_rvalid,
    output wire m_axi_hp0_rready,
    input  wire [127:0] m_axi_hp0_rdata,
    input  wire [1:0] m_axi_hp0_rresp,
    input  wire m_axi_hp0_rlast,
    output wire m_axi_hp0_awvalid,
    input  wire m_axi_hp0_awready,
    output wire [48:0] m_axi_hp0_awaddr,
    output wire [7:0] m_axi_hp0_awlen,
    output wire [2:0] m_axi_hp0_awsize,
    output wire [1:0] m_axi_hp0_awburst,
    output wire [3:0] m_axi_hp0_awcache,
    output wire [2:0] m_axi_hp0_awprot,
    output wire m_axi_hp0_wvalid,
    input  wire m_axi_hp0_wready,
    output wire [127:0] m_axi_hp0_wdata,
    output wire [15:0] m_axi_hp0_wstrb,
    output wire m_axi_hp0_wlast,
    input  wire m_axi_hp0_bvalid,
    output wire m_axi_hp0_bready,
    input  wire [1:0] m_axi_hp0_bresp,
    output wire m_axi_hp1_arvalid,
    input  wire m_axi_hp1_arready,
    output wire [48:0] m_axi_hp1_araddr,
    output wire [7:0] m_axi_hp1_arlen,
    output wire [2:0] m_axi_hp1_arsize,
    output wire [1:0] m_axi_hp1_arburst,
    output wire [3:0] m_axi_hp1_arcache,
    output wire [2:0] m_axi_hp1_arprot,
    input  wire m_axi_hp1_rvalid,
    output wire m_axi_hp1_rready,
    input  wire [127:0] m_axi_hp1_rdata,
    input  wire [1:0] m_axi_hp1_rresp,
    input  wire m_axi_hp1_rlast,
    output wire m_axi_hp2_arvalid,
    input  wire m_axi_hp2_arready,
    output wire [48:0] m_axi_hp2_araddr,
    output wire [7:0] m_axi_hp2_arlen,
    output wire [2:0] m_axi_hp2_arsize,
    output wire [1:0] m_axi_hp2_arburst,
    output wire [3:0] m_axi_hp2_arcache,
    output wire [2:0] m_axi_hp2_arprot,
    input  wire m_axi_hp2_rvalid,
    output wire m_axi_hp2_rready,
    input  wire [127:0] m_axi_hp2_rdata,
    input  wire [1:0] m_axi_hp2_rresp,
    input  wire m_axi_hp2_rlast,
    output wire m_axi_hp3_arvalid,
    input  wire m_axi_hp3_arready,
    output wire [48:0] m_axi_hp3_araddr,
    output wire [7:0] m_axi_hp3_arlen,
    output wire [2:0] m_axi_hp3_arsize,
    output wire [1:0] m_axi_hp3_arburst,
    output wire [3:0] m_axi_hp3_arcache,
    output wire [2:0] m_axi_hp3_arprot,
    input  wire m_axi_hp3_rvalid,
    output wire m_axi_hp3_rready,
    input  wire [127:0] m_axi_hp3_rdata,
    input  wire [1:0] m_axi_hp3_rresp,
    input  wire m_axi_hp3_rlast
);
    wire [3:0] arvalid_all;
    wire [3:0] arready_all;
    wire [195:0] araddr_all;
    wire [31:0] arlen_all;
    wire [2:0] arsize_all;
    wire [1:0] arburst_all;
    wire [3:0] arcache_all;
    wire [2:0] arprot_all;
    wire [3:0] rvalid_all;
    wire [3:0] rready_all;
    wire [511:0] rdata_all;
    wire [7:0] rresp_all;
    wire [3:0] rlast_all;
    assign m_axi_hp0_arvalid = arvalid_all[0:0];
    assign arready_all[0:0] = m_axi_hp0_arready;
    assign m_axi_hp0_araddr = araddr_all[48:0];
    assign m_axi_hp0_arlen = arlen_all[7:0];
    assign m_axi_hp0_arsize = arsize_all;
    assign m_axi_hp0_arburst = arburst_all;
    assign m_axi_hp0_arcache = arcache_all;
    assign m_axi_hp0_arprot = arprot_all;
    assign rvalid_all[0:0] = m_axi_hp0_rvalid;
    assign m_axi_hp0_rready = rready_all[0:0];
    assign rdata_all[127:0] = m_axi_hp0_rdata;
    assign rresp_all[1:0] = m_axi_hp0_rresp;
    assign rlast_all[0:0] = m_axi_hp0_rlast;
    assign m_axi_hp1_arvalid = arvalid_all[1:1];
    assign arready_all[1:1] = m_axi_hp1_arready;
    assign m_axi_hp1_araddr = araddr_all[97:49];
    assign m_axi_hp1_arlen = arlen_all[15:8];
    assign m_axi_hp1_arsize = arsize_all;
    assign m_axi_hp1_arburst = arburst_all;
    assign m_axi_hp1_arcache = arcache_all;
    assign m_axi_hp1_arprot = arprot_all;
    assign rvalid_all[1:1] = m_axi_hp1_rvalid;
    assign m_axi_hp1_rready = rready_all[1:1];
    assign rdata_all[255:128] = m_axi_hp1_rdata;
    assign rresp_all[3:2] = m_axi_hp1_rresp;
    assign rlast_all[1:1] = m_axi_hp1_rlast;
    assign m_axi_hp2_arvalid = arvalid_all[2:2];
    assign arready_all[2:2] = m_axi_hp2_arready;
    assign m_axi_hp2_araddr = araddr_all[146:98];
    assign m_axi_hp2_arlen = arlen_all[23:16];
    assign m_axi_hp2_arsize = arsize_all;
    assign m_axi_hp2_arburst = arburst_all;
    assign m_axi_hp2_arcache = arcache_all;
    assign m_axi_hp2_arprot = arprot_all;
    assign rvalid_all[2:2] = m_axi_hp2_rvalid;
    assign m_axi_hp2_rready = rready_all[2:2];
    assign rdata_all[383:256] = m_axi_hp2_rdata;
    assign rresp_all[5:4] = m_axi_hp2_rresp;
    assign rlast_all[2:2] = m_axi_hp2_rlast;
    assign m_axi_hp3_arvalid = arvalid_all[3:3];
    assign arready_all[3:3] = m_axi_hp3_arready;
    assign m_axi_hp3_araddr = araddr_all[195:147];
    assign m_axi_hp3_arlen = arlen_all[31:24];
    assign m_axi_hp3_arsize = arsize_all;
    assign m_axi_hp3_arburst = arburst_all;
    assign m_axi_hp3_arcache = arcache_all;
    assign m_axi_hp3_arprot = arprot_all;
    assign rvalid_all[3:3] = m_axi_hp3_rvalid;
    assign m_axi_hp3_rready = rready_all[3:3];
    assign rdata_all[511:384] = m_axi_hp3_rdata;
    assign rresp_all[7:6] = m_axi_hp3_rresp;
    assign rlast_all[3:3] = m_axi_hp3_rlast;
    bw_test_top #(.NPORTS(4)) core (
        .clk(clk),
        .rst_n(rst_n),
        .s_axil_awvalid(s_axi_ctrl_awvalid),
        .s_axil_awready(s_axi_ctrl_awready),
        .s_axil_awaddr(s_axi_ctrl_awaddr),
        .s_axil_wvalid(s_axi_ctrl_wvalid),
        .s_axil_wready(s_axi_ctrl_wready),
        .s_axil_wdata(s_axi_ctrl_wdata),
        .s_axil_wstrb(s_axi_ctrl_wstrb),
        .s_axil_bvalid(s_axi_ctrl_bvalid),
        .s_axil_bready(s_axi_ctrl_bready),
        .s_axil_bresp(s_axi_ctrl_bresp),
        .s_axil_arvalid(s_axi_ctrl_arvalid),
        .s_axil_arready(s_axi_ctrl_arready),
        .s_axil_araddr(s_axi_ctrl_araddr),
        .s_axil_rvalid(s_axi_ctrl_rvalid),
        .s_axil_rready(s_axi_ctrl_rready),
        .s_axil_rdata(s_axi_ctrl_rdata),
        .s_axil_rresp(s_axi_ctrl_rresp),
        .m_axi_arvalid(arvalid_all),
        .m_axi_arready(arready_all),
        .m_axi_araddr(araddr_all),
        .m_axi_arlen(arlen_all),
        .m_axi_arsize(arsize_all),
        .m_axi_arburst(arburst_all),
        .m_axi_arcache(arcache_all),
        .m_axi_arprot(arprot_all),
        .m_axi_rvalid(rvalid_all),
        .m_axi_rready(rready_all),
        .m_axi_rdata(rdata_all),
        .m_axi_rresp(rresp_all),
        .m_axi_rlast(rlast_all),
        .m_axi_awvalid(m_axi_hp0_awvalid),
        .m_axi_awready(m_axi_hp0_awready),
        .m_axi_awaddr(m_axi_hp0_awaddr),
        .m_axi_awlen(m_axi_hp0_awlen),
        .m_axi_awsize(m_axi_hp0_awsize),
        .m_axi_awburst(m_axi_hp0_awburst),
        .m_axi_awcache(m_axi_hp0_awcache),
        .m_axi_awprot(m_axi_hp0_awprot),
        .m_axi_wvalid(m_axi_hp0_wvalid),
        .m_axi_wready(m_axi_hp0_wready),
        .m_axi_wdata(m_axi_hp0_wdata),
        .m_axi_wstrb(m_axi_hp0_wstrb),
        .m_axi_wlast(m_axi_hp0_wlast),
        .m_axi_bvalid(m_axi_hp0_bvalid),
        .m_axi_bready(m_axi_hp0_bready),
        .m_axi_bresp(m_axi_hp0_bresp)
    );
endmodule
