"""Generate Verilog-2001 wrappers for Vivado IP Integrator module references.

IP Integrator cannot use a SystemVerilog module as a module-reference top, and it
infers AXI interfaces from per-interface port names. These wrappers split the
packed multi-port buses of bw_test_top / accel_top into s_axi_ctrl (AXI-Lite) and
m_axi_hp0..3 (AXI4, 128 bit; only hp0 carries write channels).

python kv260/gen_wrappers.py --write   regenerate rtl/kv260_*_wrapper.v
python kv260/gen_wrappers.py           exit 1 if the checked-in files are stale
"""
from pathlib import Path
import argparse
import sys

RTL = Path(__file__).resolve().parents[1] / "rtl"
AW = 49

READ = [("arvalid", 1, "out"), ("arready", 1, "in"), ("araddr", AW, "out"), ("arlen", 8, "out"),
        ("arsize", 3, "out"), ("arburst", 2, "out"), ("arcache", 4, "out"), ("arprot", 3, "out"),
        ("rvalid", 1, "in"), ("rready", 1, "out"), ("rdata", 128, "in"), ("rresp", 2, "in"), ("rlast", 1, "in")]
WRITE = [("awvalid", 1, "out"), ("awready", 1, "in"), ("awaddr", AW, "out"), ("awlen", 8, "out"),
         ("awsize", 3, "out"), ("awburst", 2, "out"), ("awcache", 4, "out"), ("awprot", 3, "out"),
         ("wvalid", 1, "out"), ("wready", 1, "in"), ("wdata", 128, "out"), ("wstrb", 16, "out"),
         ("wlast", 1, "out"), ("bvalid", 1, "in"), ("bready", 1, "out"), ("bresp", 2, "in")]
LITE = [("awvalid", 1, "in"), ("awready", 1, "out"), ("awaddr", 12, "in"), ("wvalid", 1, "in"),
        ("wready", 1, "out"), ("wdata", 32, "in"), ("wstrb", 4, "in"), ("bvalid", 1, "out"),
        ("bready", 1, "in"), ("bresp", 2, "out"), ("arvalid", 1, "in"), ("arready", 1, "out"),
        ("araddr", 12, "in"), ("rvalid", 1, "out"), ("rready", 1, "in"), ("rdata", 32, "out"),
        ("rresp", 2, "out")]
# Shared (not per-port) read-channel attributes in the packed SV interface.
SHARED = {"arsize", "arburst", "arcache", "arprot"}


def rng(width):
    return "" if width == 1 else f"[{width - 1}:0] "


def wrapper(name, top, params, ports=4, debug=False):
    lines = [f"// Generated by kv260/gen_wrappers.py; do not edit. Verilog-2001 shell for IP Integrator.",
             f"// Instantiates {top} (SystemVerilog) with {ports} HP ports; hp0 also writes.",
             f"module {name} ("]
    decl = []
    decl.append('    (* X_INTERFACE_INFO = "xilinx.com:signal:clock:1.0 clk CLK" *)')
    decl.append('    (* X_INTERFACE_PARAMETER = "ASSOCIATED_BUSIF '
                + ":".join(["s_axi_ctrl"] + [f"m_axi_hp{p}" for p in range(ports)])
                + ', ASSOCIATED_RESET rst_n" *)')
    decl.append("    input  wire clk,")
    decl.append('    (* X_INTERFACE_INFO = "xilinx.com:signal:reset:1.0 rst_n RST" *)')
    decl.append('    (* X_INTERFACE_PARAMETER = "POLARITY ACTIVE_LOW" *)')
    decl.append("    input  wire rst_n,")
    for sig, w, d in LITE:
        decl.append(f"    {'input ' if d == 'in' else 'output'} wire {rng(w)}s_axi_ctrl_{sig},")
    for p in range(ports):
        for sig, w, d in READ + (WRITE if p == 0 else []):
            decl.append(f"    {'input ' if d == 'in' else 'output'} wire {rng(w)}m_axi_hp{p}_{sig},")
    if debug:
        decl.append("    output wire dbg_logit_valid,")
        decl.append("    output wire [31:0] dbg_logit,")
        decl.append("    output wire dbg_busy,")
        decl.append("    output wire [15:0] dbg_pc,")
    decl[-1] = decl[-1].rstrip(",")
    lines += decl
    lines.append(");")
    # packed nets
    for sig, w, d in READ:
        if sig in SHARED:
            lines.append(f"    wire {rng(w)}{sig}_all;")
        else:
            lines.append(f"    wire [{ports * w - 1}:0] {sig}_all;")
    for p in range(ports):
        for sig, w, d in READ:
            if sig in SHARED:
                lines.append(f"    assign m_axi_hp{p}_{sig} = {sig}_all;")
            elif d == "out":
                lines.append(f"    assign m_axi_hp{p}_{sig} = {sig}_all[{(p + 1) * w - 1}:{p * w}];")
            else:
                lines.append(f"    assign {sig}_all[{(p + 1) * w - 1}:{p * w}] = m_axi_hp{p}_{sig};")
    plist = ", ".join(f".{k}({v})" for k, v in params.items())
    lines.append(f"    {top} #({plist}) core (")
    conns = ["        .clk(clk)", "        .rst_n(rst_n)"]
    conns += [f"        .s_axil_{sig}(s_axi_ctrl_{sig})" for sig, _, _ in LITE]
    conns += [f"        .m_axi_{sig}({sig}_all)" for sig, _, _ in READ]
    conns += [f"        .m_axi_{sig}(m_axi_hp0_{sig})" for sig, _, _ in WRITE]
    if debug:
        conns += ["        .dbg_logit_valid(dbg_logit_valid)", "        .dbg_logit(dbg_logit)",
                  "        .dbg_busy(dbg_busy)", "        .dbg_pc(dbg_pc)"]
    lines.append(",\n".join(conns))
    lines.append("    );")
    lines.append("endmodule")
    return "\n".join(lines) + "\n"


FILES = {
    "kv260_bw_wrapper.v": lambda: wrapper("kv260_bw_wrapper", "bw_test_top", {"NPORTS": 4}),
    "kv260_accel_wrapper.v": lambda: wrapper("kv260_accel_wrapper", "accel_top", {"NPORTS": 4}, debug=True),
}


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args()
    stale = []
    for fname, make in FILES.items():
        text = make()
        path = RTL / fname
        if args.write:
            path.write_text(text, encoding="utf-8")
        elif not path.exists() or path.read_text(encoding="utf-8") != text:
            stale.append(fname)
    if stale:
        print("stale:", ", ".join(stale))
        sys.exit(1)
    print("wrappers written" if args.write else "wrappers up to date")


if __name__ == "__main__":
    main()
