"""Single source of truth for the AXI-Lite register maps of the Step 3 PL IP.

Offsets are relative to each IP's AXI-Lite base address, which Vivado's address
editor assigns when the block design is built (not known here, never hard-coded).
`python kv260/regmap.py --write` regenerates rtl/kv260_regs_pkg.sv; the RTL test
runner fails if the checked-in package is stale.
"""
from dataclasses import dataclass
from pathlib import Path
import argparse
import sys


@dataclass(frozen=True)
class Reg:
    name: str
    offset: int
    access: str          # RO, RW, WO (write-only pulse bits)
    doc: str


BW_ID = 0x4B564257       # 'KVBW'
ACC_ID = 0x4B564143      # 'KVAC'
VERSION = 0x00010000

# Bandwidth / DMA-correctness test IP (milestone M1).
BW_REGS = [
    Reg("ID", 0x00, "RO", "0x4B564257 ('KVBW')"),
    Reg("VERSION", 0x04, "RO", "major<<16 | minor"),
    Reg("CTRL", 0x08, "WO", "bit0 RD_START, bit1 WR_START, bit31 SOFT_RESET (all self-clearing)"),
    Reg("STATUS", 0x0C, "RO", "bit0 RD_BUSY, bit1 WR_BUSY, [11:8] RD_ERR, [15:12] WR_ERR, bit16 CFG_ERR"),
    Reg("RD_ADDR_LO", 0x10, "RW", "read start byte address [31:0] (HP ports x beat aligned)"),
    Reg("RD_ADDR_HI", 0x14, "RW", "read start byte address [48:32]"),
    Reg("RD_BYTES", 0x18, "RW", "bytes per read pass (multiple of HP ports x beat, 64 B for 4x128 bit)"),
    Reg("RD_REPEAT", 0x1C, "RW", "number of back-to-back read passes (0 is treated as 1)"),
    Reg("WR_ADDR_LO", 0x20, "RW", "write start byte address [31:0] (beat aligned)"),
    Reg("WR_ADDR_HI", 0x24, "RW", "write start byte address [48:32]"),
    Reg("WR_BYTES", 0x28, "RW", "bytes to write (multiple of the beat)"),
    Reg("WR_SEED", 0x2C, "RW", "pattern: 32-bit word k of the write = WR_SEED + k"),
    Reg("RD_CYCLES", 0x30, "RO", "clock cycles from RD_START until the last beat"),
    Reg("RD_BEATS", 0x34, "RO", "beats received"),
    Reg("RD_SUM", 0x38, "RO", "sum of all little-endian 32-bit words read, mod 2^32"),
    Reg("WR_CYCLES", 0x3C, "RO", "clock cycles from WR_START until the last BRESP"),
    Reg("CAPS", 0x40, "RO", "[3:0] HP ports, [15:8] data width/8, [23:16] max burst beats-1"),
]

# Accelerator control (DCU); see rtl/accel_ctrl notes in rtl/README.md.
ACC_REGS = [
    Reg("ID", 0x00, "RO", "0x4B564143 ('KVAC')"),
    Reg("VERSION", 0x04, "RO", "major<<16 | minor"),
    Reg("CTRL", 0x08, "WO", "bit0 START (run program once), bit31 SOFT_RESET"),
    Reg("STATUS", 0x0C, "RO", "bit0 BUSY, bit1 DONE (sticky until START), [15:8] ERROR code (rtl/accel_core.sv)"),
    Reg("IMAGE_BASE_LO", 0x10, "RW", "DMA device address of the DDR image [31:0] (64 B aligned)"),
    Reg("IMAGE_BASE_HI", 0x14, "RW", "DMA device address of the DDR image [48:32]"),
    Reg("PROG_WORDS", 0x18, "RW", "number of 128-bit instructions in program memory"),
    Reg("TOKEN", 0x1C, "RW", "input token id (BATCH=1)"),
    Reg("POS", 0x20, "RW", "position of the token (cached rows before it)"),
    Reg("RESULT", 0x24, "RO", "argmax token of the last run"),
    Reg("CYCLES", 0x28, "RO", "clock cycles of the last run"),
    Reg("ERR_PC", 0x2C, "RO", "instruction index that raised ERROR"),
    Reg("PROG_ADDR", 0x30, "RW", "program memory pointer in 32-bit units (instruction = PROG_ADDR / 4)"),
    Reg("PROG_DATA", 0x34, "WO", "writes 32 bits at PROG_ADDR (4 writes per instruction, low first), auto-increment"),
    Reg("ROPE_ADDR", 0x38, "RW", "RoPE table pointer: 0..63 cos, 64..127 sin of the current POS"),
    Reg("ROPE_DATA", 0x3C, "WO", "writes one FP32 RoPE value at ROPE_ADDR, auto-increment"),
    Reg("ATTN_SCALE", 0x40, "RW", "FP32 bits of head_dim ** -0.5 (0x3DB504F3 for 128)"),
    Reg("CAPS", 0x44, "RO", "[3:0] HP ports, [31:16] max context rows"),
]


def check(regs):
    offsets = [r.offset for r in regs]
    assert len(set(offsets)) == len(offsets) and all(o % 4 == 0 for o in offsets), "overlapping/misaligned regs"


def sv_package():
    lines = ["// Generated by kv260/regmap.py; do not edit.", "/* verilator lint_off UNUSEDPARAM */",
             "package kv260_regs_pkg;"]
    lines.append(f"    localparam logic [31:0] BW_ID_VALUE = 32'h{BW_ID:08X};")
    lines.append(f"    localparam logic [31:0] ACC_ID_VALUE = 32'h{ACC_ID:08X};")
    lines.append(f"    localparam logic [31:0] VERSION_VALUE = 32'h{VERSION:08X};")
    for prefix, regs in (("BW", BW_REGS), ("ACC", ACC_REGS)):
        check(regs)
        for r in regs:
            lines.append(f"    localparam logic [11:0] {prefix}_{r.name} = 12'h{r.offset:03X};  // {r.access}: {r.doc}")
    lines += ["endpackage", "/* verilator lint_on UNUSEDPARAM */"]
    return "\n".join(lines) + "\n"


PKG = Path(__file__).resolve().parents[1] / "rtl" / "kv260_regs_pkg.sv"


def markdown():
    out = []
    for title, regs in (("Bandwidth test IP (KVBW)", BW_REGS), ("Accelerator control (KVAC)", ACC_REGS)):
        out += [f"### {title}", "", "| Offset | Name | Access | Meaning |", "|---|---|---|---|"]
        out += [f"| 0x{r.offset:02X} | {r.name} | {r.access} | {r.doc} |" for r in regs]
        out.append("")
    return "\n".join(out)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="regenerate rtl/kv260_regs_pkg.sv")
    parser.add_argument("--markdown", action="store_true")
    args = parser.parse_args()
    if args.markdown:
        print(markdown())
    elif args.write:
        PKG.write_text(sv_package(), encoding="utf-8")
        print(PKG)
    else:
        stale = not PKG.exists() or PKG.read_text(encoding="utf-8") != sv_package()
        print("stale" if stale else "up to date")
        sys.exit(1 if stale else 0)


if __name__ == "__main__":
    main()
